### ISSUE TITLE
Precompiled FFmpeg 6.0-latest not found

### ISSUE THREAD

**Issue by gBillal** [membraneframework/membrane_precompiled_dependency_provider#2]
Looks like the linux precompiled ffmpeg library `6.0-latest` no longer exists and replaced by `6.1-latest`.
`https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n6.0-latest-linuxarm64-gpl-shared-6.0.tar.xz` returns `404`.

**Comment by sgfn** [comment]
Hi @gBillal, thanks for the notice.

Here's a hotfix which should get merged ASAP https://github.com/membraneframework/membrane_precompiled_dependency_provider/pull/3.
We'll work on a more permanent solution as soon as we're able.

**Comment by sgfn** [comment]
Released as v0.1.1. Thanks again for the heads-up
